import { Report } from "@/lib/types";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { FileText, Save, Target } from "lucide-react";

interface ReportViewProps {
  report: Report | undefined;
}

export function ReportView({ report }: ReportViewProps) {
  if (!report) {
    return (
      <div className="flex h-full flex-col items-center justify-center text-slate-400 bg-slate-50">
        <FileText size={64} className="mb-4 text-slate-200" />
        <p className="text-lg font-medium text-slate-400">レポートを選択してください</p>
      </div>
    );
  }

  const renderContent = (content: string) => {
    return content.split('\n').map((line, i) => {
        if (line.startsWith('# ')) return <h1 key={i} className="text-2xl font-bold text-slate-800 mt-8 mb-4 flex items-center gap-2 pb-2 border-b border-slate-100">{line.replace('# ', '')}</h1>;
        if (line.startsWith('## ')) return <h2 key={i} className="text-lg font-bold text-slate-700 mt-6 mb-3 px-4 py-2 bg-indigo-50 border-l-4 border-indigo-500 rounded-r-lg">{line.replace('## ', '')}</h2>;
        if (line.startsWith('### ')) return <h3 key={i} className="text-base font-bold text-slate-600 mt-5 mb-2">{line.replace('### ', '')}</h3>;
        if (line.startsWith('* ')) return <li key={i} className="ml-6 list-disc text-slate-600 mb-1.5 leading-relaxed">{line.replace('* ', '')}</li>;
        if (line.trim() === '') return <div key={i} className="h-2" />;
        return <p key={i} className="mb-3 text-slate-600 leading-relaxed text-sm md:text-base">{line}</p>;
    });
  };

  return (
    <div className="flex flex-col h-full bg-white relative">
      {/* Header - Styled after Workspace Tab area */}
      <div className="px-8 py-6 border-b border-slate-200 flex items-center justify-between sticky top-0 bg-white z-10 shadow-sm">
        <div>
            <div className="flex items-center gap-2 text-xs font-bold text-indigo-600 uppercase tracking-widest mb-1">
                <Target size={12} />
                Weekly Strategic Insight
            </div>
            <h1 className="text-2xl font-bold text-slate-900 tracking-tight">
                {report.title}
            </h1>
        </div>
        <div className="flex flex-col items-end gap-1">
            <Badge variant="outline" className="bg-slate-50 text-slate-500 border-slate-200 font-mono text-[10px]">
                W{report.week} / {report.year}
            </Badge>
            <div className="text-[10px] text-slate-400 flex items-center gap-1">
                <Save size={10} /> Auto-archived
            </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-8 md:p-12 lg:p-16 bg-white">
        <div className="max-w-4xl mx-auto">
            <div className="bg-slate-50/50 rounded-2xl p-8 border border-slate-100 shadow-inner">
                <article className="prose prose-slate max-w-none">
                    {renderContent(report.content)}
                </article>
            </div>
            
            <div className="mt-12 pt-8 border-t border-slate-100 text-center">
                <p className="text-xs text-slate-400 italic">
                    This report was generated by the Domain AI Engine. All insights are strategic recommendations.
                </p>
            </div>
        </div>
      </div>
    </div>
  );
}